feat(LPs template)
Casa-do-Saber/courses-lp-template pull request #1
Opened 2021-07-20 22:21 UTC by a-bemporad

### Overview
- Created base for Courses LP template.

2021-07-23 03:08 UTC, Meira-JH requested changes

2021-07-23 18:08 UTC, a-bemporad commented on .env.EXAMPLE
> +LIST_SUBSC_NUMBER=
I agree, I'm gonna update it to ACTIVE_CAMPAIGN_LIST_ID

2021-07-23 18:12 UTC, a-bemporad commented on src/api/apiCasa.js
> +const API_URL = 'https://api.casadosaber.com.br';
done!

2021-07-23 18:17 UTC, a-bemporad commented on src/api/getTime.js
> +const url = 'https://worldtimeapi.org/api/timezone/america/sao_paulo';
Done!

2021-07-23 18:18 UTC, a-bemporad commented on src/components/OfferBar/Layout2.jsx
> +`;
it was a little gambiarra to test a function, but it is understood that this is not a good practice nor is it our standard! it will be fixed! same for the other four cases!

2021-07-23 18:20 UTC, a-bemporad commented on src/pages/_document.jsx
> +          {/* End Google Tag Manager (noscript) */}
this is not clear for me right now, once I am past the other stuff, can we discuss this?

2021-07-23 18:21 UTC, a-bemporad commented on src/pages/confirmacao.jsx
> +}
Understood and agreed! I still haven't got to work with this pages template specifically, but I'm gonna make it to fit our standards!

2021-07-23 18:37 UTC, a-bemporad commented on src/pages/course-name.jsx
> +  return <Page />;
I think is worth discussing this on a call.

I actually thought that on **index.jsx** this was made as a part of the rewrites() and base_path implementations. But looking into it, it's not, and actually not good hahaha. We can agree to make the _capture page_ directly on **index.jsx**. 

And just wanted to remember that right now our **/teacher-name** path, is rendering the same thing as our /**teacher-name/course-name** path. Maybe I misunderstood. But as that is what I thought we had agreed on, I decided the freelancer's approach was a neater way to make this happen, without having to import everything again. Until we make a specific teacher page.

2021-07-23 18:39 UTC, a-bemporad commented on src/pages/index.jsx
> +}
replied above!

2021-07-23 18:41 UTC, a-bemporad commented on src/pages/sales-page.jsx
> +    </>
how so? in here there's just a container inside a page, I think this one is actually right! please confirm!

2021-07-23 18:44 UTC, a-bemporad commented on src/pages/teacher-name.jsx
> +}
not clear for me what's wrong in here :( but either way it was just a placeholder, for now. I created this teacher page to avoid a 404 since our LPs path is gonna be /teacher-name/course-name. On the last Clovis I made, both **/teacher-page** and **/teacher-page/course-name** contain de capture page. If this is not right, please let me know!

2021-07-23 18:45 UTC, a-bemporad commented on src/services/gtm.js
> +};
great! I'll work on it, maybe it would be nice to create this as a new task on Jira?

2021-07-23 18:46 UTC, a-bemporad commented on src/services/useCurrentDate.js
> +}
😍

2021-07-23 18:50 UTC, a-bemporad commented on .eslintrc.json
> +    "react/react-in-jsx-scope": "off"
sadly it was not my creation, I made it using the freelancer's repo as a guideline hahah

2021-07-28 12:33 UTC, Meira-JH approved these changes

2021-07-28 12:33 UTC, Meira-JH commented on src/components/Offer/index.js
> +  const layoutOption = useLayoutChange(courseOfferDates);
that is looking elegant. Great job.

2021-07-28 12:33 UTC, Meira-JH commented on src/services/useGtm.js
> +}
nice nice!!!

2021-07-28 12:33 UTC, Meira-JH commented on src/services/useLayoutChange.js
> +    } else if (currentDate == lastDate) {
why not === instead of == ? Are the types different? If yes, cant we put them all the same?

2021-07-28 12:45 UTC, Meira-JH commented on src/pages/_document.jsx
> +          {/* End Google Tag Manager (noscript) */}
sure!

2021-07-28 12:45 UTC, Meira-JH commented on src/pages/_document.jsx
> +          {/* End Google Tag Manager (noscript) */}
but it seems that you got it!

2021-07-28 12:46 UTC, Meira-JH commented on src/pages/sales-page.jsx
> +    </>
your' right!

2021-07-28 12:51 UTC, a-bemporad commented on src/services/useLayoutChange.js
> +    } else if (currentDate == lastDate) {
I guess I forgot the third =, since they are strictly equal! nice catch!

2021-07-28 12:56 UTC, a-bemporad commented on src/api/getTime.js
> +    //NOTE: should I return something in here?
hmmm, I was thinking how to be able to notice if the api is not working, and do something about it in that case so code doesn't break, but I'm not clear about the best approach

2021-07-28 12:57 UTC, a-bemporad commented on src/components/Offer/index.js
> +  const layoutOption = useLayoutChange(courseOfferDates);
:' ) thank you!

2021-07-28 18:33 UTC, merged